version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file: .env.prod
    volumes:
      - media:/app/media
    networks:
      - coolify

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: .env.prod
    depends_on:
      - backend
    networks:
      - coolify

networks:
  coolify:

volumes:
  media:
