version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: jroots.co_db
    restart: always
    environment:
      POSTGRES_USER: jroots
      POSTGRES_PASSWORD: 3EQKw4PDoHJzUmu
      POSTGRES_DB: jroots.co
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:

